version: '2'
networks:
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.100.9.0/24
                  gateway: 172.100.9.253
services:
    dble-1:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: dble-1
        hostname: dble-1
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7131:7131"
            - "7141:7141"
        networks:
            net:
              ipv4_address: 172.100.9.1
        dns: 114.114.114.114
        working_dir: /opt
    dble-2:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: dble-2
        hostname: dble-2
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7132:7132"
            - "7142:7142"
        networks:
            net:
              ipv4_address: 172.100.9.2
        dns: 114.114.114.114
        working_dir: /opt
    dble-3:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: dble-3
        hostname: dble-3
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7133:7133"
            - "7143:7143"
        networks:
            net:
              ipv4_address: 172.100.9.3
        dns: 114.114.114.114
        working_dir: /opt
    mysql:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: mysql
        hostname: mysql
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7144:7144"
        networks:
            net:
              ipv4_address: 172.100.9.4
        dns: 114.114.114.114
        working_dir: /opt
    mysql-master1:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: mysql-master1
        hostname: mysql-master1
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7145:7145"
            - "7146:7146"
        networks:
            net:
              ipv4_address: 172.100.9.5
        dns: 114.114.114.114
        working_dir: /opt
    mysql-master2:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: mysql-master2
        hostname: mysql-master2
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7147:7147"
            - "7148:7148"
        networks:
            net:
              ipv4_address: 172.100.9.6
        dns: 114.114.114.114
        working_dir: /opt
    mysql-slave1:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: mysql-slave1
        hostname: mysql-slave1
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7149:7149"
            - "7150:7150"
        networks:
            net:
              ipv4_address: 172.100.9.7
        dns: 114.114.114.114
        working_dir: /opt
    mysql-slave2:
        image: docker-registry:5000/actiontech/balm-runtime-centos6
        container_name: mysql-slave2
        hostname: mysql-slave2
        privileged: true
        stdin_open: true
        tty: true
        volumes:
            - /opt/auto_build:/init_assets
        ports:
            - "7151:7151"
            - "7152:7152"
        networks:
            net:
              ipv4_address: 172.100.9.8
        dns: 114.114.114.114
        working_dir: /opt
