version: '2'
networks:
    net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.100.0.1/16
                  gateway: 172.100.0.253
services:
    mycat.centos6-1:
        image: centos:6  
        container_name: mycat.centos6-1
        hostname: mycat.centos6-1
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "7130:8066"
            - "7136:3306"
        networks:
            net:
              ipv4_address: 172.100.0.2
        dns: 114.114.114.114
    mycat.mysql:
        image: centos:6
        container_name: mycat.mysql
        hostname: mycat.mysql
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "7131:3306"
        networks:
            net:
              ipv4_address: 172.100.0.3
        dns: 114.114.114.114
    mycat.mysql1:
        image: centos:6
        container_name: mycat.mysql1
        hostname: mycat.mysql1
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "7132:3306"
        networks:
            net:
              ipv4_address: 172.100.0.4
        dns: 114.114.114.114
    mycat.mysql2:
        image: centos:6
        container_name: mycat.mysql2
        hostname: mycat.mysql2
        privileged: true
        stdin_open: true
        tty: true
        ports:
            - "7133:3306"
        networks:
            net:
              ipv4_address: 172.100.0.5
        dns: 114.114.114.114
    
